### ISSUE TITLE
amcheck1.5  compilation issue against PostgreSQL 12 beta1

### ISSUE THREAD

**Issue by devrimgunduz** [petergeoghegan/amcheck#17]
Hi @petergeoghegan ,

amcheck 1.5 is failing to build against PostgreSQL 12 beta1. Can you please take a look?

Thanks!

> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -O2  -I. -I./ -I/usr/pgsql-12/include/server -I/usr/pgsql-12/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o verify_nbtree.bc verify_nbtree.c
verify_nbtree.c: In function 'bt_index_check_internal':
verify_nbtree.c:230:13: warning: implicit declaration of function 'heap_open' [-Wimplicit-function-declaration]
  230 |   heaprel = heap_open(heapid, lockmode);
      |             ^~~~~~~~~
verify_nbtree.c:230:11: warning: assignment to 'Relation' {aka 'struct RelationData *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
  230 |   heaprel = heap_open(heapid, lockmode);
      |           ^
verify_nbtree.c:272:3: warning: implicit declaration of function 'heap_close'; did you mean 'pclose'? [-Wimplicit-function-declaration]
  272 |   heap_close(heaprel, lockmode);
      |   ^~~~~~~~~~
      |   pclose
verify_nbtree.c: In function 'btree_index_checkable':
verify_nbtree.c:301:7: warning: implicit declaration of function 'IndexIsValid'; did you mean 'OidIsValid'? [-Wimplicit-function-declaration]
  301 |  if (!IndexIsValid(rel->rd_index))
      |       ^~~~~~~~~~~~
      |       OidIsValid
verify_nbtree.c: In function 'bt_check_every_level':
verify_nbtree.c:520:3: warning: implicit declaration of function 'IndexBuildHeapScan' [-Wimplicit-function-declaration]
  520 |   IndexBuildHeapScan(state->heaprel, state->rel, indexinfo, true,
      |   ^~~~~~~~~~~~~~~~~~
verify_nbtree.c: In function 'bt_target_page_check':
verify_nbtree.c:844:8: warning: assignment to 'ScanKey' {aka 'struct ScanKeyData *'} from incompatible pointer type 'BTScanInsert' {aka 'struct BTScanInsertData *'} [-Wincompatible-pointer-types]
  844 |   skey = _bt_mkscankey(state->rel, itup);
      |        ^
verify_nbtree.c: In function 'bt_right_page_check_scankey':
verify_nbtree.c:1240:9: warning: returning 'BTScanInsert' {aka 'struct BTScanInsertData *'} from a function with incompatible return type 'ScanKey' {aka 'struct ScanKeyData *'} [-Wincompatible-pointer-types]
 1240 |  return _bt_mkscankey(state->rel,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
 1241 |        (IndexTuple) PageGetItem(rightpage, rightitem));
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
verify_nbtree.c: In function 'invariant_leq_offset':
verify_nbtree.c:1820:32: warning: passing argument 2 of '_bt_compare' makes pointer from integer without a cast [-Wint-conversion]
 1820 |  cmp = _bt_compare(state->rel, natts, key, state->target, upperbound);
      |                                ^~~~~
      |                                |
      |                                int16 {aka short int}
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:53: note: expected 'BTScanInsert' {aka 'struct BTScanInsertData *'} but argument is of type 'int16' {aka 'short int'}
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |                                        ~~~~~~~~~~~~~^~~
verify_nbtree.c:1820:39: warning: passing argument 3 of '_bt_compare' from incompatible pointer type [-Wincompatible-pointer-types]
 1820 |  cmp = _bt_compare(state->rel, natts, key, state->target, upperbound);
      |                                       ^~~
      |                                       |
      |                                       ScanKey {aka struct ScanKeyData *}
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:63: note: expected 'Page' {aka 'char *'} but argument is of type 'ScanKey' {aka 'struct ScanKeyData *'}
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |                                                          ~~~~~^~~~
verify_nbtree.c:1820:49: warning: passing argument 4 of '_bt_compare' makes integer from pointer without a cast [-Wint-conversion]
 1820 |  cmp = _bt_compare(state->rel, natts, key, state->target, upperbound);
      |                                            ~~~~~^~~~~~~~
      |                                                 |
      |                                                 Page {aka char *}
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:82: note: expected 'OffsetNumber' {aka 'short unsigned int'} but argument is of type 'Page' {aka 'char *'}
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |                                                                     ~~~~~~~~~~~~~^~~~~~
verify_nbtree.c:1820:8: error: too many arguments to function '_bt_compare'
 1820 |  cmp = _bt_compare(state->rel, natts, key, state->target, upperbound);
      |        ^~~~~~~~~~~
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:14: note: declared here
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |              ^~~~~~~~~~~
verify_nbtree.c: In function 'invariant_geq_offset':
verify_nbtree.c:1839:32: warning: passing argument 2 of '_bt_compare' makes pointer from integer without a cast [-Wint-conversion]
 1839 |  cmp = _bt_compare(state->rel, natts, key, state->target, lowerbound);
      |                                ^~~~~
      |                                |
      |                                int16 {aka short int}
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:53: note: expected 'BTScanInsert' {aka 'struct BTScanInsertData *'} but argument is of type 'int16' {aka 'short int'}
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |                                        ~~~~~~~~~~~~~^~~
verify_nbtree.c:1839:39: warning: passing argument 3 of '_bt_compare' from incompatible pointer type [-Wincompatible-pointer-types]
 1839 |  cmp = _bt_compare(state->rel, natts, key, state->target, lowerbound);
      |                                       ^~~
      |                                       |
      |                                       ScanKey {aka struct ScanKeyData *}
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:63: note: expected 'Page' {aka 'char *'} but argument is of type 'ScanKey' {aka 'struct ScanKeyData *'}
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |                                                          ~~~~~^~~~
verify_nbtree.c:1839:49: warning: passing argument 4 of '_bt_compare' makes integer from pointer without a cast [-Wint-conversion]
 1839 |  cmp = _bt_compare(state->rel, natts, key, state->target, lowerbound);
      |                                            ~~~~~^~~~~~~~
      |                                                 |
      |                                                 Page {aka char *}
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:82: note: expected 'OffsetNumber' {aka 'short unsigned int'} but argument is of type 'Page' {aka 'char *'}
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |                                                                     ~~~~~~~~~~~~~^~~~~~
verify_nbtree.c:1839:8: error: too many arguments to function '_bt_compare'
 1839 |  cmp = _bt_compare(state->rel, natts, key, state->target, lowerbound);
      |        ^~~~~~~~~~~
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:14: note: declared here
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |              ^~~~~~~~~~~
verify_nbtree.c: In function 'invariant_leq_nontarget_offset':
verify_nbtree.c:1862:32: warning: passing argument 2 of '_bt_compare' makes pointer from integer without a cast [-Wint-conversion]
 1862 |  cmp = _bt_compare(state->rel, natts, key, nontarget, upperbound);
      |                                ^~~~~
      |                                |
      |                                int16 {aka short int}
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:53: note: expected 'BTScanInsert' {aka 'struct BTScanInsertData *'} but argument is of type 'int16' {aka 'short int'}
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |                                        ~~~~~~~~~~~~~^~~
verify_nbtree.c:1862:39: warning: passing argument 3 of '_bt_compare' from incompatible pointer type [-Wincompatible-pointer-types]
 1862 |  cmp = _bt_compare(state->rel, natts, key, nontarget, upperbound);
      |                                       ^~~
      |                                       |
      |                                       ScanKey {aka struct ScanKeyData *}
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:63: note: expected 'Page' {aka 'char *'} but argument is of type 'ScanKey' {aka 'struct ScanKeyData *'}
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |                                                          ~~~~~^~~~
verify_nbtree.c:1862:44: warning: passing argument 4 of '_bt_compare' makes integer from pointer without a cast [-Wint-conversion]
 1862 |  cmp = _bt_compare(state->rel, natts, key, nontarget, upperbound);
      |                                            ^~~~~~~~~
      |                                            |
      |                                            Page {aka char *}
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:82: note: expected 'OffsetNumber' {aka 'short unsigned int'} but argument is of type 'Page' {aka 'char *'}
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |                                                                     ~~~~~~~~~~~~~^~~~~~
verify_nbtree.c:1862:8: error: too many arguments to function '_bt_compare'
 1862 |  cmp = _bt_compare(state->rel, natts, key, nontarget, upperbound);
      |        ^~~~~~~~~~~
In file included from verify_nbtree.c:29:
/usr/pgsql-12/include/server/access/nbtree.h:777:14: note: declared here
  777 | extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
      |              ^~~~~~~~~~~
make[1]: *** [<builtin>: verify_nbtree.o] Error 1
make[1]: *** Waiting for unfinished jobs....
verify_nbtree.c:230:13: warning: implicit declaration of function 'heap_open' is invalid in C99 [-Wimplicit-function-declaration]
                heaprel = heap_open(heapid, lockmode);
                          ^
verify_nbtree.c:230:11: warning: incompatible integer to pointer conversion assigning to 'Relation' (aka 'struct RelationData *') from 'int' [-Wint-conversion]
                heaprel = heap_open(heapid, lockmode);
                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
verify_nbtree.c:272:3: warning: implicit declaration of function 'heap_close' is invalid in C99 [-Wimplicit-function-declaration]
                heap_close(heaprel, lockmode);
                ^
verify_nbtree.c:301:7: warning: implicit declaration of function 'IndexIsValid' is invalid in C99 [-Wimplicit-function-declaration]
        if (!IndexIsValid(rel->rd_index))
             ^
verify_nbtree.c:520:3: warning: implicit declaration of function 'IndexBuildHeapScan' is invalid in C99 [-Wimplicit-function-declaration]
                IndexBuildHeapScan(state->heaprel, state->rel, indexinfo, true,
                ^
verify_nbtree.c:844:8: warning: incompatible pointer types assigning to 'ScanKey' (aka 'struct ScanKeyData *') from 'BTScanInsert' (aka 'struct BTScanInsertData *') [-Wincompatible-pointer-types]
                skey = _bt_mkscankey(state->rel, itup);
                     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
verify_nbtree.c:1240:9: warning: incompatible pointer types returning 'BTScanInsert' (aka 'struct BTScanInsertData *') from a function with result type 'ScanKey' (aka 'struct ScanKeyData *') [-Wincompatible-pointer-types]
        return _bt_mkscankey(state->rel,
               ^~~~~~~~~~~~~~~~~~~~~~~~~
verify_nbtree.c:1820:59: error: too many arguments to function call, expected 4, have 5
        cmp = _bt_compare(state->rel, natts, key, state->target, upperbound);
              ~~~~~~~~~~~                                        ^~~~~~~~~~
/usr/pgsql-12/include/server/access/nbtree.h:777:1: note: '_bt_compare' declared here
extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
^
verify_nbtree.c:1839:59: error: too many arguments to function call, expected 4, have 5
        cmp = _bt_compare(state->rel, natts, key, state->target, lowerbound);
              ~~~~~~~~~~~                                        ^~~~~~~~~~
/usr/pgsql-12/include/server/access/nbtree.h:777:1: note: '_bt_compare' declared here
extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
^
verify_nbtree.c:1862:55: error: too many arguments to function call, expected 4, have 5
        cmp = _bt_compare(state->rel, natts, key, nontarget, upperbound);
              ~~~~~~~~~~~                                    ^~~~~~~~~~
/usr/pgsql-12/include/server/access/nbtree.h:777:1: note: '_bt_compare' declared here
extern int32 _bt_compare(Relation rel, BTScanInsert key, Page page, OffsetNumber offnum);
^
7 warnings and 3 errors generated.

**Comment by petergeoghegan** [comment]
Hi @devrimgunduz 

The amcheck_next extension isn't supposed to work with Postgres 12, or Postgres 11. The contrib version of amcheck is at least as effective at verification in Postgres versions 11+.

Please only build packages for 9.4 - Postgres 10.

Thanks
