### ISSUE TITLE
Doc: make it clearer what (if any) additional checks amcheck_next provides over upstream

### ISSUE THREAD

**Issue by mbanck** [petergeoghegan/amcheck#19]
`README.md` says: "amcheck_next also exists to provide additional verification checks that do not yet appear in stable PostgreSQL contrib/amcheck releases.", however at this point it is unclear whether that is actually the case.

**Comment by petergeoghegan** [comment]
Fair point. I cleared this up in the README file by pushing a fix just now.

Thanks
