### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Harrykris** [petergeoghegan/amcheck#8]
Can you please help us with a test case to reproduce the Logical corruption. We did try with couple of scenarios, however they turned out to be physical one.

We're trying to check, how amcheck can help to detect the logical corruption, so that we can include this utility as a part of healthcheck scripts.

Any help will be appreciated.

**Comment by petergeoghegan** [comment]
What type of logical corruption?

Please don't abuse the issues page in this manner.
